package org.firstinspires.ftc.teamcode;

import android.annotation.SuppressLint;

import com.acmerobotics.roadrunner.geometry.Pose2d;
import com.qualcomm.robotcore.hardware.HardwareMap;
import com.qualcomm.robotcore.util.ElapsedTime;

import org.firstinspires.ftc.robotcore.external.Telemetry;
import org.firstinspires.ftc.teamcode.drive.StandardTrackingWheelLocalizer;

import java.io.BufferedWriter;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;

@SuppressLint("DefaultLocale")
// File writing code stolen from https://discord.com/channels/225450307654647808/225451520911605765/936127511086116924
public class AutoTrainer {
    StandardTrackingWheelLocalizer localizer;
    Telemetry telemetry;
    ElapsedTime timer;
    Pose2d lastPose = new Pose2d();
    Pose2d startPose;

    Pose2d lastCapturedPose;

    public int poseIndex = 0;
    String trajSequenceString;

    final String filePath = "/storage/self/primary/";
    File file = new File(filePath + "PoseSequence.csv");
    BufferedWriter writer = null;

    // Constructor
    public AutoTrainer(HardwareMap hwmap, Telemetry telemetry, Pose2d startPose){
        this.localizer = new StandardTrackingWheelLocalizer(hwmap);
        this.telemetry = telemetry;
        this.startPose = startPose;
        lastCapturedPose = startPose;
        trajSequenceString = "TrajectorySequence autoGeneratedTrajectory = drive.trajectorySequenceBuilder(" + poseToString(startPose) + ")\n";
        localizer.setPoseEstimate(startPose);
        timer = new ElapsedTime();
        initializeWriter();
    }
    // Called in init in the constructor
    void initializeWriter(){
        try {
            writer = new BufferedWriter(new FileWriter(file));
            writer.write("time taken after running, code, x, y, heading");
            writer.write("\n");

        } catch (IOException e) {
            e.printStackTrace();
        }
    }
    // Call this when the program is stopped
    public void closeWriter(){
        // Finish up the trajsequence string
        trajSequenceString += ".build();";
        // And stick it on the end of the file
        try{

        writer.write("\n\n\n");
        writer.write(String.format("%.1f", timer.seconds()) + "," + "\"" + trajSequenceString + "\"");

        } catch (IOException e) {
            e.printStackTrace();
        }
        try {
            writer.flush();
            writer.close();
        } catch (IOException e) {
            e.printStackTrace();
        }
    }

    public void update(){
        localizer.update();
        lastPose = localizer.getPoseEstimate();
        telemetry.addData("current pose", poseToString(lastPose));
        telemetry.addData("estimated tangent", Math.toDegrees(getEstimatedEndTangent()));
        telemetry.addData("trajSequenceString", trajSequenceString);
    }


    public String poseToString(Pose2d pose){
        return String.format("new Pose2d(%.2f, %.2f, Math.toRadians(%.1f))", pose.getX(), pose.getY(), Math.toDegrees(pose.getHeading()));
    }

    // This stuff is just for making the trajSequence string
    double getAngleBetweenPoses(Pose2d initialPose, Pose2d finalPose){
        double deltaX = finalPose.getX() - initialPose.getX();
        double deltaY = finalPose.getY() - initialPose.getY();

        return Math.atan2(deltaY, deltaX);
    }
    // Shorthand for the previous method
    double getEstimatedEndTangent(){
        return getAngleBetweenPoses(lastCapturedPose, lastPose);
    }

    public void addPoseToFile(){
        // Set the tangent to start if it's the first pose being captured
        if (poseIndex == 0){
            trajSequenceString += ".setTangent(Math.toRadians(" + String.format("%.1f", Math.toDegrees(getEstimatedEndTangent())) + "))" + "\n";
        }
        // Tell it we've just added a new pose
        poseIndex ++;
        // Now the normal stuff that happens every time
        try {
            // Add quotes (the \" parts) because the pose has commas in it that would mess up the csv file otherwise
            writer.write(
                    String.format("%.2f", timer.seconds()) + "," + "\"" + poseToString(lastPose) + "\"" + ", "
                    + String.format("%.2f", lastPose.getX()) + ", "
                    + String.format("%.2f", lastPose.getY()) + ", "
                    + String.format("%.1f", Math.toDegrees(lastPose.getHeading())));
            writer.write("\n");
        } catch (IOException e) {
            e.printStackTrace();
        }
        // Tack on another splineToSpline to the big auto-generated code chunk
        trajSequenceString += ".splineToSplineHeading(" + poseToString(lastPose)
                + ", Math.toRadians(" + String.format("%.1f", Math.toDegrees(getEstimatedEndTangent())) + "))"
                + "\n";

        lastCapturedPose = lastPose;
    }
}
