package org.firstinspires.ftc.teamcode.auto;

import com.acmerobotics.roadrunner.geometry.Pose2d;
import com.outoftheboxrobotics.photoncore.PhotonCore;
import com.qualcomm.robotcore.eventloop.opmode.Autonomous;
import com.qualcomm.robotcore.eventloop.opmode.Disabled;
import com.qualcomm.robotcore.eventloop.opmode.LinearOpMode;

import org.firstinspires.ftc.teamcode.drive.SampleMecanumDrive;
import org.firstinspires.ftc.teamcode.trajectorysequence.TrajectorySequence;

//@Disabled
@Autonomous
public class BaseAuto extends LinearOpMode {
    // Pre init
    SampleMecanumDrive drive;
    Pose2d startpos = new Pose2d(0,0,Math.toRadians(-90));

    @Override
    public void runOpMode(){
        // Init
        drive = new SampleMecanumDrive(hardwareMap);
        drive.setPoseEstimate(startpos);

        TrajectorySequence autoGeneratedTrajectory = drive.trajectorySequenceBuilder(new Pose2d(0.00, 0.00, Math.toRadians(-90.0)))
                .setTangent(Math.toRadians(137.3))
                .splineToSplineHeading(new Pose2d(-18.20, 16.77, Math.toRadians(218.8)), Math.toRadians(137.3))
                .splineToSplineHeading(new Pose2d(-21.80, 49.23, Math.toRadians(179.8)), Math.toRadians(96.3))
                .splineToSplineHeading(new Pose2d(3.08, 67.05, Math.toRadians(98.5)), Math.toRadians(35.6))
                .splineToSplineHeading(new Pose2d(23.17, 23.24, Math.toRadians(24.9)), Math.toRadians(-65.4))
                .splineToSplineHeading(new Pose2d(2.98, 3.98, Math.toRadians(275.5)), Math.toRadians(-136.4))
                .build();

        waitForStart();
        if (opModeIsActive()){
            // Auto code
            drive.followTrajectorySequence(autoGeneratedTrajectory);
        }
    }
}